version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
    ports:
      - "8080:80"
    container_name: front-end-container
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    container_name: back-end-container
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=todo_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: HKdfnbb6-op
      MYSQL_DATABASE: todo_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pmypassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
