name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug Secrets (Optional, ensure secrets are accessible)
      - name: Debug Secrets
        run: echo "Using DockerHub Username: ${{ secrets.DOCKER_USERNAME }}"

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the frontend image
      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-devops-frontend:latest ./front-end

      # Step 5: Push the frontend image to DockerHub
      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-devops-frontend:latest

      # Step 6: Build the backend image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-devops-backend:latest ./Backend

      # Step 7: Push the backend image to DockerHub
      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-devops-backend:latest
