name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Load variables from .env file
      - name: Load environment variables
        run: |
          if [ -f .env ]; then
            export $(cat .env | xargs)
            echo "DOCKER_USERNAME=$DOCKER_USERNAME"
          else
            echo ".env file not found! Exiting..."
            exit 1
          fi

      # Login to DockerHub using loaded credentials
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build the Docker image for frontend
      - name: Build Frontend Image
        run: |
          docker build -t $DOCKER_USERNAME/my-devops-frontend:latest ./front-end

      # Push the frontend image to DockerHub
      - name: Push Frontend Image
        run: |
          docker push $DOCKER_USERNAME/my-devops-frontend:latest

      # Build the Docker image for backend
      - name: Build Backend Image
        run: |
          docker build -t $DOCKER_USERNAME/my-devops-backend:latest ./Backend

      # Push the backend image to DockerHub
      - name: Push Backend Image
        run: |
          docker push $DOCKER_USERNAME/my-devops-backend:latest
